# Generated by Django 5.1.1 on 2024-10-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='userId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='customusermodel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
